# Site settings
title: Owlery Club
header-img: img/main_blog.jpg
email: info@owlery.club
copyright_name: Owlery Club
description: "Software Engineering + Design + Big Data"
baseurl: "/blog"
url: "https://mapineda.github.io"
twitter_username: marcoapineda13
github_username:  mapineda
facebook_username:
email_username:  info@owlery.club

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
