# Site settings
title: Owlery Club
header-img: img/main-blog-bg.jpg
email: info@owlery.club
copyright_name: Owlery Club
description: "In the professional world of tomorrow, you have to know two things, the basics of business and the basics of coding."
baseurl: "/"
url: "http://owlery.club"
twitter_username: marcoapineda13
github_username:  mapineda
facebook_username:
email_username:  hire@marcopineda.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
